#!/usr/bin/env bash
# publish.sh — commit posts.json and push to GitHub so Vercel auto-deploys

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_ROOT"

TODAY=$(date +"%Y-%m-%d")
POSTS_FILE="src/data/posts.json"

echo "📦 Publishing updated posts.json to GitHub..."
echo "   Project: $PROJECT_ROOT"
echo "   Date: $TODAY"

# Check if there's anything to commit
if git diff --quiet "$POSTS_FILE" 2>/dev/null && git diff --cached --quiet "$POSTS_FILE" 2>/dev/null; then
    echo "ℹ️  No changes in $POSTS_FILE — nothing to publish"
    exit 0
fi

git add "$POSTS_FILE"
git commit -m "content: auto-publish article for $TODAY

Generated by daily_run.py + generate_article.py
Topics: roofing, HVAC, storm damage, insurance, financing, weather
City rotation across 20 Texas cities

Co-Authored-By: automation <noreply@texaspropertyhelp.com>"

git push origin HEAD

echo ""
echo "✅ Published! Vercel will auto-deploy in ~60 seconds."
echo "   Check: https://texaspropertyhelp.com/updates/"
